WB-1185: Fix changesets release process
Includes the following fixes:

1. Use ss-agent so that the release PR can self-update and initiate test runs

2. Fix that message so it doesn’t say ${GITHUB_REPOSITORY} and markdown formatting issues with the link

3. Remove lerna script from package.json

4. Add experimental flag to include bump updates to dependents. This is
   added so we avoid having mismatches between dependencies in webapp
   (we used a similar approach with lerna).

Issue: WB-1185

Merge then verify if the next release process works smoothly.

diff --git a/.github/workflows/node-ci-push.yml b/.github/workflows/node-ci-push.yml
--- a/.github/workflows/node-ci-push.yml
+++ b/.github/workflows/node-ci-push.yml
@@ -137,3 +137,53 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
         autoAcceptChanges: true
+
+  publish_to_branch:
+    needs: [prime_cache_primary]
+    name: Publish to branch
+    env:
+      CI: true
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        node-version: [12.x]
+    steps:
+    - uses: webfactory/ssh-agent@v0.4.1
+      with:
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+    - name: Clone repository
+      run: git clone git@github.com:Khan/wonder-blocks.git .
+
+      # For PRs, we can use github.head_ref to get the branch that the PR
+      # is made from. We cannot use github.ref as that points to the PR, not
+      # its branch. For pushes, we have to get the branch name from GITHUB_REF
+      # which, instead of just being a branch name, is of the form
+      # refs/heads/<BRANCH NAME>
+      # Note if we end up with a blank branch name, we quit as otherwise, we
+      # would update the default branch, which is not what we want at all.
+    - name: Determine checkout branch
+      run: |
+        _PUBLISH_BRANCH=$(test $GITHUB_HEAD_REF && echo $GITHUB_HEAD_REF || echo $GITHUB_REF | sed -e "s/refs\/heads\///g")
+        test $_PUBLISH_BRANCH || exit 1
+        echo "PUBLISH_BRANCH=$_PUBLISH_BRANCH" >> $GITHUB_ENV
+    - name: Checkout via SSH
+      run: git checkout ${{ env.PUBLISH_BRANCH }}
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Detect changes
+      run: echo "HAS_CHANGES=$(git status --porcelain | wc -l | xargs echo)" >> $GITHUB_ENV
+    - name: Commit changes
+      if: env.HAS_CHANGES != '0'
+      # If we have changes, we push them and then fail out. This prevents
+      # us from running more testing than we want since the push will
+      # trigger another test run anyway.
+      run: |
+        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+        git config user.name "$GITHUB_ACTOR"
+        git add dist
+        git commit -m "Updating branch with build artifacts (https://github.com/Khan/wonder-blocks/actions/runs/${{ github.run_id }})"
+        git push
+        exit 1
