Merge all jobs that publish to npm into a single workflow file - required for Trusted Publishing

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -59,9 +59,17 @@ jobs:
   # https://github.com/changesets/action#usage
   release:
     name: Release
-    runs-on: ubuntu-latest
+    if: |
+      (github.event_name == 'workflow_dispatch' && inputs.run_type == 'release') ||
+      (github.event_name == 'push' && github.ref == 'refs/heads/main')
+    runs-on: ${{ matrix.os }}
     permissions:
-      id-token: write # required for publishing to npm with provenance
+      id-token: write # For trusted publishing to npm (includes provenance)
+      contents: write # For GitHub pages and creating release PRs
+    strategy:
+        matrix:
+            os: [ubuntu-latest]
+            node-version: [20.x]
     steps:
       - uses: actions/checkout@v4
         with:
@@ -131,3 +139,137 @@ jobs:
           SLACK_TITLE: "New Wonder Blocks release!"
           SLACK_FOOTER: Wonder Blocks Slack Notification
           MSG_MINIMAL: true
+
+  # Publishes a PR's changes to an npm snapshot. This allows for easy testing of
+  # PR code in a host applicaiton without doing a release.
+  publish_snapshot:
+    name: Publish npm snapshot
+    # We don't publish snapshots on draft PRs or
+    # on the main Changeset "Version Packages" PR
+    if: |
+      github.event.pull_request.draft == false
+      && !startsWith(github.head_ref, 'changeset-release/')
+    runs-on: ${{ matrix.os }}
+    permissions:
+      id-token: write # required for publishing to npm with provenance
+      issues: write # required because we write a comment on the PR
+      pull-requests: write # required because we create a comment on the PR
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        node-version: [20.x]
+    steps:
+      # We need to checkout all history, so that the changeset tool can diff it
+      - name: Checkout current commit
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - name: Ensure main branch is avaialble
+        run: |
+          REF=$(git rev-parse HEAD)
+          git checkout main
+          git checkout $REF
+
+      # Helper to get the URL of the current run, if we need it.
+      - name: Get workflow run URL
+        id: get-run-url
+        run: echo "run_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
+
+      # We need to see if any releases are in progress.
+      # We do not want to try and publish anything if a publish is
+      # pending. We fail here, but we make sure to update the
+      # PR comment later. This has to come after the checkout.
+      - name: Check for release
+        id: check-release
+        env:
+            GH_TOKEN: ${{ github.token }}
+        run: |
+            # Releases are triggered by merging "Version Packages" PRs.
+            # So we look for instances of the release.yml workflow, with
+            # a title containing "Version Packages", that are in progress.
+            release_count=$(gh run list --workflow release.yml --json status,displayTitle --jq '[.[] | select(.status == "in_progress" and ((.displayTitle | contains("Version Packages")) or (.displayTitle | contains("RELEASING:"))))] | length')
+            echo "release_count=$release_count" >> $GITHUB_OUTPUT
+            if [ "$release_count" -ne 0 ]; then
+              echo "Error: There are $release_count releases in progress."
+              exit 1
+            else
+              echo "No releases in progress."
+            fi
+
+      - name: Use Node.js ${{ matrix.node-version }} & Install & cache node_modules
+        uses: ./.github/actions/shared-node-cache
+        with:
+          node-version: ${{ matrix.node-version }}
+
+      - name: Publish snapshot release to npm
+        id: publish-snapshot
+        run: ./utils/publish/publish-snapshot.sh # All config is via Github env vars
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+      - name: Calculate short SHA for this commit
+        id: short-sha
+        run: echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
+
+      # Note: these two actions are locked to the latest version that were
+      # published when @jeremy (Jeremy Wiebe) created the original job in Perseus.
+      - name: Find existing comment
+        # Even if we're failing, we want to update the comments.
+        if: always()
+        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
+        id: find-comment
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-author: "github-actions[bot]"
+          body-includes: "npm Snapshot:"
+
+      - name: Create or update npm snapshot comment - Success
+        if: steps.publish-snapshot.outputs.npm_snapshot_tag != ''
+        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-id: ${{ steps.find-comment.outputs.comment-id }}
+          edit-mode: replace
+          body: |
+            ## npm Snapshot: Published
+            🎉 Good news!! We've packaged up the latest commit from this PR (${{
+            steps.short-sha.outputs.short_sha }}) and published all packages with changesets to npm.
+
+            You can install the packages in `frontend` by running:
+            ```sh
+            ./dev/tools/deploy_wonder_blocks.js --tag="${{
+            steps.publish-snapshot.outputs.npm_snapshot_tag }}"
+            ```
+
+            Packages can also be installed manually by running:
+            ```sh
+            pnpm add @khanacademy/wonder-blocks-<package-name>@${{
+            steps.publish-snapshot.outputs.npm_snapshot_tag }}
+            ```
+      - name: Create or update npm snapshot comment - Failure
+        if: steps.publish-snapshot.outputs.npm_snapshot_tag == ''
+        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-id: ${{ steps.find-comment.outputs.comment-id }}
+          edit-mode: replace
+          body: |
+              ## npm Snapshot: **NOT** Published
+              🤕 Oh noes!! We couldn't find any changesets in this PR (${{
+              steps.short-sha.outputs.short_sha }}). As a result, we did **not** publish an npm snapshot for you.
+
+      - name: Create or update npm snapshot comment - failure, concurrent with release
+        if: failure() && steps.check-release.outputs.release_count != '0'
+        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
+        with:
+            issue-number: ${{ github.event.pull_request.number }}
+            comment-id: ${{ steps.find-comment.outputs.comment-id }}
+            edit-mode: replace
+            body: |
+                # npm Snapshot: **NOT** Published
+
+                🤕 Oh noes!! We couldn't publish an npm snapshot for you because
+                there is a release in progress. Please wait for the release to
+                finish, then retry this workflow.
+
+                [View the workflow run](${{ steps.get-run-url.outputs.run_url }})
